[classification]
categories = ["Facture","Devis","Bon de livraison","Contrat client","Contrat d'embauche","KPI","Bon de commande","Relevé d'activité","Rapport d'intervention","Note de frais"]

[folders]
source_folder_path = ""

[ai]
api_key = ""
